name: xb
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# App versioning
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0

  # State Management & Navigation
  get: ^4.6.6

  # Utilities
  http: ^1.2.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  shimmer:
  cached_network_image:
  
  # Payment Gateway
  razorpay_flutter: ^1.3.7
  
  # Additional utilities
  intl: ^0.18.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/XB logo.png
    - assets/XB Square-1 1.png
    - assets/XB in text.png
    - assets/Pi7_XB in text.png
    - assets/food-bg.jpg
    - assets/Group_1.png
    - assets/Group_2.png
    - assets/Group_3.png
    - assets/images/G1.png
    - assets/images/G2.png
    - assets/images/G3.png
    - assets/images/G4.png
    - assets/images/G5.png
    - assets/images/G6.png
    - assets/images/G8.png
    - assets/images/back.jpg
    - assets/images/asjkdkjad.png
    - assets/images/welcomeImage.jpg
